site_name: Smile Prediction
repo_url: https://github.com/lgrosjean/drug-molecule-properties
repo_name: lgrosjean/drug-molecule-properties
edit_uri: ""

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            new_path_syntax: yes
        watch:
          - smiley

theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - header.autohide
  icon:
    repo: fontawesome/brands/git-alt

nav:
  - Home: README.md
  - Getting started:
      - Installation: installation.md
      - Train your models: training.md
  - References:
      - train.md
      - learner.md
      - model.md
      - dataset.md
      - utils.md

markdown_extensions:
  - meta
  - admonition
  - markdown_include.include:
      base_path: docs
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed

extra_css:
  - css/termynal.css
  - css/custom.c

extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
  - js/termynal.js
  - js/custom.js
